### PR TITLE
fix issue #9 bow.py RuntimeError: tried to construct a tensor from a …

### PR DESCRIPTION
**Pull request by sojvai**
fix issue #9 

It seems cuda tensor doesn't accept numpy array as a parameter.
convert it to python list worked.

### CODE REVIEW

**Comment by aconneau** [comment]
Could you try 

`idx = torch.from_numpy(permutation[i:i + self.batch_size]).long().cuda()`

instead and let me know if that fixes the issue? I think it would make more sense to use the "from_numpy" function here.

**Comment by sojvai** [comment]
Yeah. That worked!

**Comment by sojvai** [comment]
@aconneau updated the PR based on your suggestion.

**Comment by aconneau** [comment]
Thanks! There may be other lines like this that are not pytorch 0.2 compatible. I'll merge your pull request and track the rest myself.

**Pull request merged**
